Fix Python bindings for static member functions Frme::DH() and Frame::DH_Craig1989()
orocos/orocos_kinematics_dynamics pull request #363
Opened 2021-10-13 10:17 UTC by meyerj

Those are static member functions of `KDL::Frame` and hence need to be declared to pybind11 with `def_static()` instead of `def()`:

https://github.com/orocos/orocos_kinematics_dynamics/blob/a789adafa8d09f9d098810b4f9b845fc1a77f389/orocos_kdl/src/frames.hpp#L647-L701

Before:
```py
>>> import PyKDL
>>> PyKDL.Frame().DH_Craig1989(0.,0.,0.,0.)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: DH_Craig1989(): incompatible function arguments. The following argument types are supported:
    1. (self: float, arg0: float, arg1: float, arg2: float) -> PyKDL.Frame

Invoked with: [[           1,           0,           0;
            0,           1,           0;
            0,           0,           1]
[           0,           0,           0]], 0.0, 0.0, 0.0, 0.0
```

With this patch:
```py
>>> import PyKDL
>>> PyKDL.Frame().DH_Craig1989(0.,0.,0.,0.)
[[           1,          -0,           0;
            0,           1,          -0;
            0,           0,           1]
[           0,          -0,           0]]
>>> PyKDL.Frame.DH_Craig1989(0.,0.,0.,0.)
[[           1,          -0,           0;
            0,           1,          -0;
            0,           0,           1]
[           0,          -0,           0]]
>>> 

```

2021-10-14 12:17 UTC, MatthijsBurgh requested changes
I think we should both test calling the method on the class and on an instance.

As in python, the added test succeeds with and without the patch. While calling the method on an instance fails (which you showed in your comment), which is not tested right now.

2021-10-14 12:17 UTC, MatthijsBurgh commented on python_orocos_kdl/tests/framestest.py
> +        f = Frame.DH(0.0, pi/2, 0.36, 0.0)
This variable seems to be unused

2021-11-02 17:06 UTC, MatthijsBurgh commented
@meyerj have you been able to check my last commit?

2021-11-02 18:09 UTC, meyerj commented
> @meyerj have you been able to check my last commit?

Yes, all fine for me. Thanks!

2021-11-02 18:09 UTC, merged